### PR TITLE
Simple Start Page

### PR DESCRIPTION
**Pull request by Brendan-Schuetze**
This would function as a simple start page for the nEXT browser. It shows commonly used keyboard shortcuts, and resizes with viewport changes.

### CODE REVIEW

**Comment by Brendan-Schuetze** [comment]
My apologies for my limited knowledge of HTML and CSS. I just wanted to create something simple with the same style as the nEXT homepage as a starting point for later development.

Seems like there is demand for this: https://github.com/nEXT-Browser/nEXT/issues/23

**Comment by jmercouris** [comment]
Hey! Looks good to me! Thank you so much for your contribution! I will actually be inverting the color and making it as plain as possible to reduce loading time, but it includes the core information that a user needs, so it's a good start!

**Comment by jmercouris** [comment]
Hi Brendan, I've changed the page a little bit, but I actually really liked the theme that you had setup, so I left it that way. I've made the file size a little bit smaller, it is around 1kb now, what do you think of how it looks? is it okay?

**Comment by Brendan-Schuetze** [comment]
👍 Looks good to me. Using the text logo makes a lot of sense for file size purposes.

**Pull request merged**
